[634]
1 = { field = "", type = "render_anim_sequences" }
2 = { field = "", type = "skip_short" }
3 = { field = "", type = "skip_short" }
4 = { field = "", type = "skip_short" }
5 = { field = "", type = "skip_short" }
6 = { field = "", type = "skip_short" }
7 = { field = "", type = "skip_short" }
8 = { field = "", type = "skip_short" }
9 = { field = "", type = "skip_short" }
26 = { field = "", type = "skip_2_bytes" }
27 = { field = "", type = "render_anim_transforms" }
28 = { field = "", type = "skip_12_bytes" }
29 = { field = "", type = "skip_byte" }
30 = { field = "", type = "skip_short" }
31 = { field = "", type = "skip_byte" }
32 = { field = "", type = "skip_short" }
33 = { field = "", type = "skip_short_signed" }
34 = { field = "", type = "skip_byte" }
35 = { field = "", type = "skip_short" }
36 = { field = "", type = "skip_short_signed" }
37 = { field = "", type = "skip_byte" }
38 = { field = "", type = "skip_short" }
39 = { field = "", type = "skip_short" }
40 = { field = "", type = "skip_short" }
41 = { field = "", type = "skip_short" }
42 = { field = "", type = "skip_short" }
43 = { field = "", type = "skip_short" }
44 = { field = "", type = "skip_short" }
45 = { field = "", type = "skip_short" }
46 = { field = "", type = "skip_short" }
47 = { field = "", type = "skip_short" }
48 = { field = "", type = "skip_short" }
49 = { field = "", type = "skip_short" }
50 = { field = "", type = "skip_short" }
51 = { field = "", type = "skip_short" }
52 = { field = "", type = "skip_render_52" }
53 = { field = "", type = "skip" }
54 = { field = "", type = "skip_2_bytes" }
55 = { field = "", type = "skip_byte_short" }
56 = { field = "", type = "skip_render_56" }
